name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - LeeXDA21
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to help the Unbeyond Team squash the bugs.
  - type: textarea
    id: tele-user
    attributes:
      label: What is your Telegram Username?
      placeholder: LeeXDA18 (Make sure to include the @, as if you were mentioning yourself)
  - type: dropdown
    id: device-model
    attributes:
      label: Device
      description: What is your Model Number?
      options:
      - SM-G970F (Galaxy S10e)
      - SM-G973F (Galaxy S10)
      - SM-G975F (Galaxy S10+)
      - SM-G980F (Galaxy S20 4G)
      - SM-G981B (Galaxy S20 5G)
      - SM-G985F (Galaxy S20+ 4G)
      - SM-G986B (Galaxy S20+ 5G)
      - SM-G988B (Galaxy S20 Ultra 5G)
      - SM-G991B (Galaxy S21 5G)
      - SM-G996B (Galaxy S21+ 5G)
      - SM-G998B (Galaxy S21 Ultra 5G)
      - SM-S901B (Galaxy S22 5G)
      - SM-S906B (Galaxy S22+ 5G)
      - SM-S908B (Galaxy S22 Ultra 5G)
    validations:
      required: true
  - type: dropdown
    id: rom-version
    attributes:
      label: ROM Variant
      description: Which ROM are you experiencing an issue on?
      options:
      - BeyondROM
      - UnboundROM
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the bug and how to reproduce it in as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: bug-desc-cont
    attributes:
      label: Bug Visual Description
      description: Please upload some screenshots/video of the bug you are reporting onto your Google Drive, and provide the link. **MUST BE A G-DRIVE LINK**
    validations:
      required: true
  - type: textarea
    id: bug-logfile
    attributes:
      label: Log File(s)
      description: Please use the LoggingKit provided from this Hub, and upload the log from "log-all" to your google drive, and provide the link. **MUST BE A G-DRIVE LINK**
    validations:
      required: true
  - type: checkboxes
    id: is-rom-bug
    attributes:
      label: Additional checks
      options:
      - label: I have checked other bug reports and this is not a duplicate.
        required: true
      - label: This is a bug in a rom maintained by The Unbeyond Team and NOT present in any other ROM.
        required: true
      - label: You understand and declare that if any information provided here is incorrect or instructions have not been followed correctly that it can lead to you being permanently banned from all Unbeyond owned servers.
        required: true
