---
name: Feature Request
about: Create a Feature Request to help us add extra goodies to the ROM.
title: "[FEATURE] Feature Name"
labels: ''
assignees: ''

---

**Describe the feature**
Describe your feature request here. [e.g. Native Blur]

**Possible Visualization**
Example ways to visualizate the request:
1. Find a screenshot of feature
2. Capture a video screenshot of feature
3. Draw a concept of feature
4. or... be creative :)

**Expected behavior**
A clear description of what you expected to happen
.

**Smartphone (please complete this feature following information part if you want device spesific):**
 - Device: [e.g. Galaxy S20+ 5G]
 - Model: [e.g. G986B]

**Origin of Feature**
- Add feature of origin device brand, device model and (if its possible) firmware link.
