name: Feature & Enhancements request
description: File a feature request
title: "[Enhancement]: "
labels: ["enhancement"]
assignees:
  - LeeXDA21
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to help improve Unbound with additional features.
  - type: dropdown
    id: typeoffeature
    attributes:
      label: Feature Category
      description: Please select the category that best suits your feature request.
      options:
      - Camera
      - User Interface
      - Mode of an App. (Eg. A Camera Mode)
      - Additional setting
      - ROM Control
      - Other
    validations:
      required: true
  - type: dropdown
    id: device-model
    attributes:
      label: Device
      description: What is your Model Number?
      options:
      - SM-G980F (Galaxy S20 4G)
      - SM-G981B (Galaxy S20 5G)
      - SM-G985F (Galaxy S20+ 4G)
      - SM-G986B (Galaxy S20+ 5G)
      - SM-G988B (Galaxy S20 Ultra 5G)
    validations:
      required: true
  - type: dropdown
    id: rom-version
    attributes:
      label: Unbound Version
      description: What version of Unbound are you using?
      options:
      - V1.0.0
      - V1.1.0
      - V1.2.0
      - V1.3.0
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature and how it works and how it would benefit future updates of the ROM in as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: feat-desc-cont
    attributes:
      label: Feature Visual Description
      description: Please upload some screenshots/video of the requested feature onto your Google Drive, and provide the link. **MUST BE A G-DRIVE LINK**
    validations:
      required: true
  - type: checkboxes
    id: is-rom-bug
    attributes:
      label: Additional checks
      options:
      - label: I have checked other current feature requests and can confirm that this is not a duplicate request.
        required: true
      - label: This is currently NOT a feature in Project Unbound.
        required: true
      - label: I can confirm that this feature has not been requested before, and has not been rejected in the past.
        required: true
